### ISSUE TITLE
[feat]storageAdapter Configuration Option

### ISSUE THREAD

**Issue by 509dave16** [segmentio/sovran-react-native#25]
It would be great if a `storageAdapter` configuration option could be supported for constructing `SovranStorage`. Currently `@react-native-async-storage/async-storage` is used as the storage mechanism. But it would great to be able to utilize faster storage libraries like [MMKV](https://github.com/mrousavy/react-native-mmkv) which is 30x faster than `AsyncStorage`. Then in `@segment/analytics-react-native@2.0` a `storageAdapter` client option could be added. Let me know what you think! If you would like, I could try and help contribute to this effort.

**Comment by oscb** [comment]
Hey David! This is a great idea, we actually wanted to use MMKV initially and @alanjcharles had a pretty complete implementation of it already, but last minute decided to use AsyncStorage for the initial release since JSI was still experimental back then. This is in our plans and one of the reasons why we structured the `Persistor` right now the way it is. 

Given that JSI is more or less stable at RN 0.68 we will circle back to this when we get the chance, but happy to hear interest in this!

**Comment by 509dave16** [comment]
@oscb Really appreciate you taking the time to look at my feature request! It is great to know that Segment has had plans to support MMKV. Our React Native app that integrates `@segment/analytics-react-native` is using MMKV right now. And we are upgrading `segment/analytics-react-native` from `1.5.1` to `2.1.12`. Our hope was that we could have `@segment/sovran-react-native` also use MKKV in order to have the best performance and have one 1 less Native Module to deal with.

In any case, we'll be looking forward to hearing more about the transition to MMKV in the future!

**Comment by 509dave16** [comment]
@oscb Just a heads up our Consumer Platform Team at Gopuff requested that I patch `segment/sovran-react-native` to use MMKV instead of Async Storage. Reason being that we migrated to MMKV from Async Storage due to the huge boost in performance. Which you can see in the following screenshots:

##iOS
![gopuff-app-mkkv-ios-benchmark](https://user-images.githubusercontent.com/2925882/168678339-e924dbb4-be39-4269-8efa-74cc859a12b8.png)

##Android
![gopuff-app-mmkv-android-benchmark](https://user-images.githubusercontent.com/2925882/168678389-dd53afe5-a226-475f-8090-69b79e91c0fe.png)

**Comment by 509dave16** [comment]
@oscb Correction. We realized that you developed a `config.persist.persistor` option. So we really just need to patch `@segment/analytics-react-native`. Apologies for the confusion.

**Comment by oscb** [comment]
Yes! You should only need to implement this interface: https://github.com/segmentio/sovran-react-native/blob/fc7b4f01ac6f0d3da889718c3fa9ab49383119e6/src/persistor/persistor.ts#L20 

This is awesome data btw. Did you find any complication switching to the JSI architecture in your application? Curious about your experience on it. Is it being actively used in the public version of GoPuff?

**Comment by 509dave16** [comment]
@oscb , MMKV has been in use in Gopuff's app for almost 6 months now. @vincentvella was responsible for the migration from Async Storage. He is also the engineer responsible for the app's upgrade to RN 0.68. And he is the one who requested I do the patching such that MMKV is used ;) .
